### ISSUE TITLE
AttributeError: 'list' object has no attribute 'timeout'

### ISSUE THREAD

**Issue by ch3njust1n** [ch3njust1n/papers_are_all_you_need#8]
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/justin/opt/anaconda3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Users/justin/opt/anaconda3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/justin/opt/anaconda3/lib/python3.9/threading.py", line 910, in run
    self.run()
  File "/Users/justin/opt/anaconda3/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/justin/Documents/dev/papers_are_all_you_need/papers/utils.py", line 248, in save_paper
    self._target(*self._args, **self._kwargs)
  File "/Users/justin/Documents/dev/papers_are_all_you_need/papers/utils.py", line 248, in save_paper
    status = download(url, save_dir, filename)
  File "/Users/justin/Documents/dev/papers_are_all_you_need/papers/utils.py", line 222, in download
    status = download(url, save_dir, filename)
  File "/Users/justin/Documents/dev/papers_are_all_you_need/papers/utils.py", line 222, in download
    with urllib.request.urlopen(url) as resp, open(save_path, 'wb') as out:
  File "/Users/justin/opt/anaconda3/lib/python3.9/urllib/request.py", line 214, in urlopen
    with urllib.request.urlopen(url) as resp, open(save_path, 'wb') as out:
  File "/Users/justin/opt/anaconda3/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
    return opener.open(url, data, timeout)
  File "/Users/justin/opt/anaconda3/lib/python3.9/urllib/request.py", line 507, in open
  File "/Users/justin/opt/anaconda3/lib/python3.9/urllib/request.py", line 507, in open
    req.timeout = timeout
    req.timeout = timeout
AttributeError: 'list' object has no attribute 'timeout'
AttributeError: 'list' object has no attribute 'timeout'
```

**Comment by ch3njust1n** [comment]
Issue was with CVPR url key-value as list value. Fixed by assuming urls are either strings or lists and handling as lists.
